# Basic web setup
# Normally, you should use https and have this listen on a higher
# port and reverse proxy it behind nginx or Apache
BaseURL="http://localhost"
ListenAddress="127.0.0.1"
Port=80

# These are used for signing SAML assertions, etc
KeyFile="idp-key.pem"
CertFile="idp-cert.pem"

# Location of SAML SP metadata (*.xml)
MetadataDirectory="metadata"

# Location of plugin directory
PluginDirectory="plugins"

# Debug logging
Debug=false

# Session/cookie configuration
RedisURI="localhost:6379"
CookieLifetime="168h"

# LDAP configuration
LDAPHost="127.0.0.1" # If using LDAPS, this will be used to verify the server's cert
LDAPPort=389
LDAPS=false
LDAPRootCA="ldap-root.pem" # Must be provided if LDAPS is true

# if PasswordChangeAsUser=false, then this should be an
# administrative user who can modify the password attributes
LDAPBindDN="admin"
LDAPBindPW="hunter2"
LDAPUsernameAttribute="uid"
LDAPGroupAttribute="memberOf"
LDAPUserFilter="(objectClass=user)"
LDAPBaseDN=[
    "ou=people,dc=example,dc=com",
]
# Groups found with the GroupAttribute above will only be included if they
# have one of these DNs as their suffix
LDAPGroupDN=[
    "ou=public groups,dc=example,dc=com",
]

# Enable AD compatibility mode
# This also requires that the bind user has been delegated the ability
# to change user passwords in the BaseDNs above if SelfServe=true
LDAPActiveDirectory=false

# Enable user self-serve features (password change)
SelfServe=true

# Password policy
# If implemented by the server, errors will be shown to the client
# if their new password does not meet the server's requirements
# but you should replicate the configuration here to the best
# of your ability to improve the error messages
PasswordMinLength=8
PasswordMustCapital=false
PasswordMustNumbers=false
PasswordMustSymbol=false

# if true, we attempt to bind as the user to change their password
# instead of doing it as the BindDN user
PasswordChangeAsUser=true

# All plugin configuration must be specified like this
# The plugin name is _always_ the filename of the plugin
# without the trailing .so
[plugins.plugin_aws]
AccountID="1234567890"      # AWS account ID, without dashes
ProviderName="saml-idp"     # name of the identity provider configured in AWS

    # Group-AWS Role mappings are defined as follows
    [[plugins.plugin_aws.role]]
    Group="admin"         # LDAP group
    Role="saml-admin"     # AWS role name

# G Suite plugin requires the Domain option
[plugins.plugin_gsuite]
Domain="example.com"

# You can choose to define specific configuration for each
# service provider so that you can disable IDP Initiated
# SSO or set a nicer display name
[[metadata]]
EntityID="https://someprovider.com/sso/saml"
IDPInitiated=true
DisplayName="Provider Name"